setup/urls.py
from django.contrib import admin
from django.urls import path
#Importar a função de views
from Blog.views import Livros_list,Home,Cadastro,Editar,Deletar,BuscaCliente,Logout

urlpatterns = [
    path('admin/', admin.site.urls),    
    
    #path da classe
    path('livro_home', Home.as_view(), name="home_blog"),
    path('livro_tabela/', Livros_list.as_view(), name="lista_livro" ),
    path('livro_form/', Cadastro.as_view(), name="livro_create"),
    path('livro_editar/<int:pk>', Editar.as_view(), name="livro_update"),
    path('livro_deletar/<int:pk>', Deletar.as_view(), name='livro_excluir'),
    path('',BuscaCliente.as_view(),name='busca_cliente'),
    path('cliente_sair/',Logout.as_view(), name='cliente_sair')
]

Blog/models.py
from django.db import models

# Create your models here.
class Livro(models.Model):
    # Campos que representam as colunas da tabela 'Livro' no banco de dados
    nome_livro = models.CharField(max_length=100) # Nome do livro, string de até 100 caracteres
    nome_autor = models.CharField(max_length=100) # nome do autor, string de até 100 caracteres
    sobrenome_autor = models.CharField(max_length=100) # sobrenome do autor, string de até 100 caracteres
    


    def __str__(self):
        """
        Método que retorna uma representação amigável do objeto Livro.
        Isso é útil no painel administrativo do Django e ao depurar.
        """
        return f"{self.nome_livro}"

    class Meta:
        """
        A classe Meta é uma classe interna que fornece metadados sobre o modelo.
        """
        verbose_name = "Livro" # Nome singular amigável para o modelo no painel administrativo
        verbose_name_plural = "Livros" # Nome plural amigável para o modelo no painel administrativo
        ordering = ['nome_livro'] # Define a ordem padrão dos registros ao consultá-los
        # Os registros serão ordenados primeiro pelo nome, depois pelo sobrenome.

class Cliente(models.Model):
    # Campos que representam as colunas da tabela 'Livro' no banco de dados
    nome = models.CharField(max_length=100) # Nome do livro, string de até 100 caracteres
    sobrenome = models.CharField(max_length=100) # Sobrenome do cliente, string de até 100 caracteres
    email = models.EmailField(unique=True) # Email do cliente, deve ser único e formatado como email
    cpf = models.CharField(max_length=11, unique=True) # CPF do cliente, string de 11 caracteres, deve ser único
    


    def __str__(self):
        """
        Método que retorna uma representação amigável do objeto Cliente.
        Isso é útil no painel administrativo do Django e ao depurar.
        """
        return f"{self.nome} {self.sobrenome} ({self.cpf})"

    class Meta:
        """
        A classe Meta é uma classe interna que fornece metadados sobre o modelo.
        """
        verbose_name = "Cliente" # Nome singular amigável para o modelo no painel administrativo
        verbose_name_plural = "Clientes" # Nome plural amigável para o modelo no painel administrativo
        ordering = ['nome', 'sobrenome'] # Define a ordem padrão dos registros ao consultá-los
        # Os registros serão ordenados primeiro pelo nome, depois pelo sobrenome.

Blog/forms.py
from django import forms #Importar o forms
from .models import Livro, Cliente#Importa o modelo (ex: Livro)
class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro #Modelo (Classe do model)
        fields = [
            'nome_livro',
            'nome_autor',
            'sobrenome_autor'
        ]

        #Opcional - Personlização do input do formulario
        widgets = {
            "nome_livro": forms.TextInput(attrs={"class": "form-control","placeholder": "Digite o nome do livro"}),
            "nome_autor": forms.TextInput(attrs={"class":"form-control","placeholder": "Digite o nome do Autor"}),
            "sobrenome_autor": forms.TextInput(attrs={"class": "form-control","placeholder": "Digite o sobrenome do Autor"})
        }

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente #Modelo (Classe do model)
        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'email'
        ]

        #Opcional - Personlização do input do formulario
        widgets = {
            "nome": forms.TextInput(attrs={"class": "form-control","placeholder": "Digite seu nome"}),
            "sobrenome": forms.TextInput(attrs={"class":"form-control","placeholder": "Digite seu Sobrenome"}),
            "cpf": forms.TextInput(attrs={"class": "form-control","placeholder": "___.___.___-__"}), # Exemplo de placeholder para CPF
            "email": forms.EmailInput(attrs={"class": "form-control","placeholder": "email@example.com"}), # Usando EmailInput
        }

Blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,View #Listview - Lista os dados a partir de uma classe
from django.urls import reverse_lazy
from .models import Livro, Cliente
from .forms import LivroForm    


# Create your views here.

#Classe da pagina principal
class Home(ListView):
    def get(self,request):
        return render(request, 'Blog/home_blog.html')

class Livros_list(ListView):
    #a ferramenta listview permite (model,template_name)
    #Conecta ao modelo de banco de dados
    model = Livro #retorna uma lista chamamda cliente_list

    #Conecta ao arquivo html do templates
    template_name = 'Blog/list_livro.html'

class Cadastro(CreateView):
    model = Livro
    form_class = LivroForm
    template_name = 'Blog/forms_livro.html'   #Gera o template do formulario
    success_url = reverse_lazy('lista_livro') #Redireciona para a pagina da tabela apos o cadastro

class Editar(UpdateView):
    model = Livro
    form_class = LivroForm
    template_name = 'Blog/forms_livro.html'
    success_url = reverse_lazy('lista_livro')

class Deletar(DeleteView):
    model = Livro
    template_name = 'Blog/delete_livro.html'
    success_url = reverse_lazy('lista_livro')

    #Trabalhando com sessoes
class BuscaCliente(View):
    #metodo que renderiza nosso formulario de autenticação
    def get(self, request):
        return render(request, 'Blog/livro_busca_form.html')
    
    #A partir daqui vamos:
    #Identificar o email e o cpf do formulario, 
    #identificar o cliente e criar a sessao
    def post(self, request):
        email = request.POST.get('email')#Guada email digitado no formulario
        cpf = request.POST.get('cpf')#Guarda cpf digitado no formulario

        if email and cpf: #verifica se o email e cpf existem
            #Guada as informações dos clientes (nosso_cliente)
            nosso_cliente = Cliente.objects.filter(email=email, cpf=cpf).first() #Pega o primerio cliente com o email e cpf
            if nosso_cliente: 
                #Vamos criar as sessoes
                request.session['nome_cliente'] = nosso_cliente.nome
                request.session['sobrenome_cliente'] = nosso_cliente.sobrenome
                titulo = 'Cliente encontrado!'
                return render(request, 'Blog/livro_busca_form.html',{'cliente':nosso_cliente, 'title':titulo})

            else: 
                erro_message = "Nenhum cliente encontrado."
                return render(request,'Blog/livro_busca_form.html', {'mensagem':erro_message})
        else: 
            erro_message = "Por favor, informe um email e cpf para consulta"
            return render(request, 'Blog/livro_busca_form.html', {'mensagem':erro_message})
        
#Calsse que encerra a sessão
class Logout(View):
    #Metodo que verifica e encerra a sessão
    def get(self, request):
        if 'nome_cliente' in request.session:
            del request.session['nome_cliente']
        if 'sobrenome_cliente' in request.session:
            del request.session['sobrenome_cliente']

        erro_message = 'Você foi desconectado!'
        return render(request, 'Blog/livro_busca_form.html', {'mensagem': erro_message})

Blog/templates/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alexandria</title>
    <link rel="stylesheet" href="{% static 'css/livros.css' %}">

</head>
<body>
    <header>
        <!-- Encaixe do cabeçalho -->
       {% include 'componentes/header.html' %}
    </header>
    <main>
    {% block content %} {% endblock %}
    </main>
    <footer>
        {% include 'componentes/footer.html' %}
    </footer>
</body>
</html>

Blog/templates/blog/delete_livro.html
{% extends 'base.html' %}

{% block content %}

<section class="sec_del row d-flex justify-content-sm-center text-center mt-5 ">
    <div class="col-sm-10 align-items-center">    
        <h1 >Deletar Livro</h1>        
        <p>Tem certeza que deseja deletar o Livro "{{ livro.nome_livro }}"?</p> 
        
        <form method="post" class="align-items-center">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Deletar</button>
            <a href="{% url 'lista_livro' %} " class="btn btn-dark btn-sm">Cancelar</a>
        </form>        
    </div>
</section>


{% endblock %}

Blog/templates/blog/forms_livro.html
{% extends 'base.html' %}
{% block title %}Cadastro{% endblock %}
{% block content %}

<section>
    <div class="titulo text-center my-4">
        <h2>Cadastro de Livros</h2>
    </div>
</section>

<section class="container">
    <form method="post" class="p-4 bg-light rounded shadow-sm">
        {% csrf_token %}

        <!-- Linha 1 -->
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="{{ form.nome_livro.id_for_label }}"><strong>Título do Livro:</strong></label>
                {{ form.nome_livro }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.nome_autor.id_for_label }}"><strong>Nome do Autor:</strong></label>
                {{ form.nome_autor }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.sobrenome_autor.id_for_label }}"><strong>Sobrenome do Autor:</strong></label>
                {{ form.sobrenome_autor }}
            </div>
        </div>

        <!-- Botão -->
        <div class="row">
            <div class="col text-center">
                <button class="btn btn-dark px-5" type="submit">Cadastrar</button>
            </div>
        </div>
    </form>
</section>

{% endblock %}

Blog/templates/blog/home_blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="home">
    <section class="boas-vindas fade-in">
        <h1>Bem-vindo ao Alexandria</h1>
        <p>Explore um universo de livros recomendados especialmente para você.</p>
        <a href="{% url 'livro_create' %}" class="botao-livros">Cadastrar Livros</a>
    </section>
</main>
{% endblock %}

Blog/templates/blog/list_livro.html
{% extends 'base.html' %}

{% block content %}
    <section class="titulo">
        <div>
            <h2>Livros</h2>
            <a href="{% url 'livro_create'%}" class="botao-cadastro">Cadastrar</a>
        </div>
    </section>
    <section>
        <table>
            <tr>
                <th>Nome do livro</th>
                <th>Nome do Autor</th>
                <th>Sobrenome do Autor</th>
            </tr>
            {% for livro in livro_list %}
            <tr>
                <td>{{livro.nome_livro}}</td>
                <td>{{livro.nome_autor}}</td>
                <td>{{livro.sobrenome_autor}}</td>
            <td>
                <a href="{% url 'livro_update' livro.id %}">Editar</a>
                <a href="{% url 'livro_excluir' livro.id %}">Excluir</a>
            </td>
            </tr>
            {% endfor  %}
        </table>  
    </section>
{% endblock %}

Blog/templates/blog/livro_busca_form.html
{% extends 'base.html' %}

{% block content %}
<div class="login-container">
    <div class="login-box">
        <h2 class="login-title">Acesse sua conta</h2>
        <form action="{% url 'busca_cliente' %}" method="post">
            {% csrf_token %}
            <input type="email" name="email" placeholder="Seu e-mail" required>
            <input type="text" name="cpf" placeholder="Seu CPF" required>
            <button type="submit">Entrar</button>
        </form>

        {% if mensagem %}
            <div class="mensagem-erro">
                {{ mensagem }}
            </div>
        {% endif %}

        {% if cliente %}
            <hr>
            <h3>{{ title }}</h3>
            <p><strong>Nome:</strong> {{ cliente.nome }} {{ cliente.sobrenome }}</p>
            <a href="{% url 'home_blog' %}" class="btn-home">Ir para o Home</a>
        {% endif %}
    </div>
</div>
{% endblock %}

Blog/templates/componentes/footer.html
<footer class="footer">
    <p>Senac/2025</p>
</footer>

Blog/templates/componentes/header.html
{% load static %}
<header class="header">
  <div class="logo">
    <img src="{% static 'img/logo.png' %}" alt="Logo Alexandria" class="logo-img">
    {% if request.session.nome_cliente %}
    <a href="{% url 'home_blog' %}">Alexandria</a>
    {% else %}
    <span class="link-bloqueado-titulo">Alexandria</span>
    {% endif %}
  </div>

  <nav class="nav-links">
  {% if request.session.nome_cliente %}
      <a href="{% url 'lista_livro' %}">Livros</a>
      <a href="{% url 'livro_create' %}">Registro</a>
      <p>{{ request.session.nome_cliente }} {{ request.session.sobrenome_cliente }}</p>
      <a href="{% url 'cliente_sair' %}">Sair</a>
  {% else %}
      <span class="link-bloqueado">Livros</span>
      <span class="link-bloqueado">Registro</span>
  {% endif %}
</nav>
</header>